version: '3'

services:
  crowi:
    build:
      context: ./docker-crowi/alpine
      dockerfile: Dockerfile
    environment:
      - MATHJAX=1
      - PLANTUML_URI=http://localhost:18080
        #    env_file: .env
    ports:
      - 3000:3000
    volumes:
      - crowi-data:/data

  db:
    image: mongo:3.6.5
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:4.0.9-alpine

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.4
    environment:
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    entrypoint:
      - bash
      - -c
      - >-
        elasticsearch-plugin list | grep -q analysis-kuromoji
        || elasticsearch-plugin install analysis-kuromoji
        && exec $$0 $$@
    command:
      - /bin/bash
      - bin/es-docker

  plantuml:
    image: plantuml/plantuml-server:jetty
    ports:
      - 18080:8080

volumes:
  crowi-data:
    driver: local

  mongo-data:
    driver: local
